apiVersion: apps/v1
kind: Deployment
metadata:
  name: cal
spec:
  selector:
    matchLabels:
      app: cal
  template:
    metadata:
      labels:
        app: cal
    spec:
      containers:
      - name: cal
        image: seun007/cal:${{ .Values.image.tag }}
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        ports:
        - containerPort: 3000
