name: Deployment Workflow
on:
  push:
    branches:
      - master

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: "Greetings"
        run: |
          echo "--- Greetings ----"
      
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Create version number"
        run: |
          echo "APP_VERSION=${RANDOM}" >> $GITHUB_ENV

          echo ${{ env.APP_VERSION }}

      - name: checks out the repository
        uses: actions/checkout@v3
                     

      - name: "Logs into docker"
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}  
      
      - name: "Build the image"
        run: |
          echo ${{ env.APP_VERSION }}
          sudo docker build -t seun007/cal:${{ env.APP_VERSION }} .
      - name: "Push the image to docker hub" 
        run: |
            docker push seun007/cal:${{ env.APP_VERSION }}

    
      - name: starting minikube
        id: minikube
        uses: medyagh/setup-minikube@latest

    
      - name: Get Minikube status
        run: minikube status
    
      - name: Get cluster info
        run: kubectl get nodes
    
      -  name: Get Kubernetes pods
         run: |
            kubectl apply -f caldeploy.yaml
            kubectl apply -f calsvc.yaml
            kubectl get pods -A
            kubectl get svc
    
      - name: Get Minikube IP
        run: echo ${{ steps.minikube.outputs.ip }}

  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - name: install helm chart
       uses: BlindfoldedSurgery/github-action-helm@v0.3.0
       with:
        subcommand: upgrade
        ref: .
        release_name: tested
        # namespace: testns
        atomic: true
        install: true
        kubeconfig: ${{ secrets.KUBECONFIG_RAW }}   